---
title: "Conferences"
---

## <span style="color:dodgerblue">**Talk content and location**

<span style="color:purple">*Co-production and Development of the Multistage Cognitive Screen – Stroke (MCS-Stroke)* -- July 2025

-   Organisation for Psychological Research into Stroke (OPSYRIS) 2025: see it [here](https://osf.io/vz5wr)

<span style="color:purple">*Neuropsychological Assessment of Executive Function* -- December 2024

-   University of Malta guest lecture, June 2024: see it [here](https://osf.io/zwgp6)

<span style="color:purple">*Comparing the Oxford Digital Multiple Errands Test (OxMET) to a real-life version* -- July 2024

-   Neuropsychological Rehabilitation Special Interest Group conference (NR-SIG), Coimbra, June 2024: see it [here](https://osf.io/fxyn5)

<span style="color:purple">*The Oxford Digital Multiple Errands Test (OxMET)* -- April 2024

-   British Neuropsychological Society (BNS) - April 2024: see it [here](https://osf.io/qmvgs).

<span style="color:purple">*The Oxford Digital Multiple Errands Test (OxMET)* -- July 2023

-   Organisation for Psychological Research into Stroke (OPSYRIS) 2023: see it [here](https://osf.io/nt8xw)


## <span style="color:dodgerblue">**Poster content and location**
<span style="color:purple">*The Mini-Oxford Cognitive Screen (Mini-OCS): A very brief cognitive screen for use in chronic stroke* -- September 2025

-   Federation of the European Societies of Neuropsychology (FESN) - September 2025: see it [here](https://osf.io/k86t3).

<span style="color:purple">*Development and validation of an IRT and theory-based Oxford Cognitive Screen short form (OCS-GP) for use in primary care* -- July 2024

-   International Neuropsychological Society - July 2024: see it [here](https://osf.io/kru4a).

<span style="color:purple">*Comparing the Oxford Digital Multiple Errands Test (OxMET) to a real-life version* -- July 2024

-   UK Stroke Forum - November 2023: see it [here](https://osf.io/tv873)

<span style="color:purple">*Development and validation of an IRT and theory-based Oxford Cognitive Screen short form (OCS-GP) for use in primary care* -- September 2023

-   Federation of the European Societies of Neuropsychology (FESN) - September 2023: see it [here](https://osf.io/n8ws7).

<span style="color:purple">*Development and validation of an IRT and theory-based Oxford Cognitive Screen short form (OCS-GP) for use in primary care* -- July 2023

-   Organisation for Psychological Research into Stroke (OPSYRIS) 2023: see it [here](https://osf.io/n8ws7)

<span style="color:purple">*Predicting ADLs and subjective cognitive failures with the Oxford Digital Multiple Errands Test (OxMET)* -- November 2022

-   UK Stroke Forum - November 2022: see it [here](https://osf.io/dvmbf)

<span style="color:purple">*Cultural adaptation of the Oxford Digital Multiple Errands Test (OxMET) for an English speaking North American population* -- July 2022

-   Rehabilitation Engineering and Assistive Technology Society of North America - July 2022: see it [here](https://osf.io/94ye8)

<span style="color:purple">*Validation of the UK English Oxford Cognitive Screen-Plus (OCS-Plus) in Subacute and Chronic Stroke* -- July 2022

-   International Neuropsychological Society - July 2022: see it [here](https://osf.io/73m6k)

<span style="color:purple">*Associations Between the Oxford Digital Multiple Errands Test and Broad Functional Outcome Measures in Subacute Stroke* -- July 2022

-   International Neuropsychological Society - July 2022: see it [here](https://osf.io/uvnb8)


<span style="color:purple">*Ecological validity of the Oxford Digital Multiple Errands Test (OxMET) in subacute stroke: Associations with measures of functional ability* -- December 2021

-   UK Stroke Forum - December 2021: see it [here](https://osf.io/rfcg7)

<span style="color:purple">*Automated scoring of the OCS-Plus Figure Copy task* -- December 2020

-   UK Stroke Forum - December 2020: see it [here](https://mfr.osf.io/render?url=https%3A%2F%2Fosf.io%2F7uagh%2Fdownload)

<span style="color:purple">*The Oxford Cognitive Screen - Plus (OCS-Plus)* -- December 2019

-   UK Stroke Forum - December 2019: see it [here](https://osf.io/3kugq?show=view&view_only=)

<span style="color:purple">*Multiverse Analysis of Validation of Executive Functioning Tests* -- October 2019

-   Organisation for Psychological Research into Stroke (OPSYRIS): see it [here](https://osf.io/k5nmw?show=view&view_only=)

<span style="color:purple">*The Oxford Competency Assessment (COMPASS)* -- September 2019

-   Federation of the European Societies of Neuropsychology (FESN) - September 2019: see it [here](https://osf.io/n83ad?show=view&view_only=)

<span style="color:purple">*MSc Dissertation* -- July 2019

-   Department of Experimental Psychology, Uni. of Oxford: see it [here](https://osf.io/k5nmw?show=view&view_only=)

<span style="color:purple">*Oxford Digital Multiple Errands Test* -- April 2019

-   British Neuropsychology Society (BNS): see it [here](https://osf.io/2c46u?show=view&view_only=)
