---
title: "Personal Repository for Publications"
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

## <span style="color:black">**Preprints:**
# **2025**
[Access](https://osf.io/preprints/psyarxiv/vygbf_v1) **Webb, S. S.**, Jespersen, A., Grammatikos, P., Hobden, G., Chiu, E. G., Payne, F., … Demeyere, N. (2025, July 28). The Oxford COMPASS: A Brief Cognitive Screen to help guide Competency Assessments. *psyarxiv*. [DOI: 10.31234/osf.io/vygbf_v1](https://doi.org/10.31234/osf.io/vygbf_v1)

[Access](https://doi.org/10.31234/osf.io/ym7wj_v1) Cowen, K., Tabone, F., **Webb, S. S.**, Kusec, A., DaSilva, R., Thomas, R., … Vancleef, K. (2025, June 10). Reliability and Validity of the Oxford Visual Perception Screen in Sub-Acute Adult Stroke Survivors. *psyarxiv*. [DOI: 10.31234/osf.io/ym7wj_v1](https://doi.org/10.31234/osf.io/ym7wj_v1)

[Access](https://osf.io/preprints/psyarxiv/yb3fe) **Webb, S. S.,** Burns, S. P., & Demeyere, N. (2024, September 18). New normative data and convergent validity for the MET-Home revised in English speaking neurologically healthy adults and stroke survivors. *psyarxiv*. [DOI: 10.31234/osf.io/yb3fe](https://doi.org/10.31234/osf.io/yb3fe)

[Access](https://doi.org/10.1101/2025.06.04.25328952)  Cowen, K., Tabone, F., **Webb, S. S.,** Kusec, A., DaSilva, R., Thomas, R., Demeyere, N., Shaw, L., & Vancleef, K. (2025). Accuracy of the Oxford Visual Perception Screen. *medRxiv*. [DOI:10.1101/2025.06.04.25328952](https://doi.org/10.1101/2025.06.04.25328952)


---

## <span style="color:black">**Registered Reports:**
# **2025**
[Access](https://doi.org/10.1016/j.cortex.2025.05.005) Moore, M. J., Hobden, G., **Webb, S. S.,** Couwels, I., & Mattingley, J., Demeyere, N. (2025). Burning houses revisited: Unconscious preferences not specifically associated with semantic content or visuospatial neglect. *Cortex*, [DOI:10.1016/j.cortex.2025.05.005](https://doi.org/10.1016/j.cortex.2025.05.005).
 
---

## <span style="color:black">**Peer-Reviewed Publications:**
# **2025**
[Access](https://doi.org/10.1177/23969873251358811) **Webb SS**, Sun L, Tang EYH, Demeyere N. The mini-Oxford cognitive screen (Mini-OCS): A very brief cognitive screen for use in chronic stroke. *Eur Stroke J*. 2025 Jul 27:23969873251358811. Epub ahead of print. PMCID: PMC12301230.[DOI: 10.1177/23969873251358811](https://doi.org/10.1177/23969873251358811)


[Access](https://doi.org/10.1523/JNEUROSCI.2048-24.2025) Pearce, D. J., Loughnane, G. M., Chong, T. T. J., Demeyere, N., Mattingley, J. B., Moore, M. J., ... & Bellgrove, M. A. (2025). Target selection signals causally influence human perceptual decision making. *Journal of Neuroscience*, [DOI:10.1523/JNEUROSCI.2048-24.2025](https://doi.org/10.1523/JNEUROSCI.2048-24.2025). 



# **2024**
[Access](https://www.tandfonline.com/doi/full/10.1080/09602011.2024.2344326?src=exp-la) **Webb, S. S.,** & Demeyere, N. (2024). Comparing the Oxford Digital Multiple Errands Test (OxMET) to a real-life version: convergence, feasibility, and acceptability. *Neuropsychological Rehabilitation*, [DOI:10.1080/09602011.2024.2344326](https://doi.org/10.1080/09602011.2024.2344326).  

[Access](https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/jnp.12369) Roberts, R., Vohora, R., **Webb, S. S.,** & Demeyere, N. (2024). Validating the OCS‐Plus against a clinical standard: A brief report. *Journal of Neuropsychology*. [DOI:10.1111/jnp.12369](https://doi.org/10.1111/jnp.12369)

# **2023**
[PDF](https://www.demeyerelab.org/wp-content/papercite-data/pdf/p_cultural_2023.pdf) A. P., P., Venkateswaran, P., Vijayanand, S., **Webb, S. S.**, Ramkumar, S., C. R., S. and Demeyere, N.  (2023). The cultural and linguistic adaptation of the Oxford Cognitive Screen to Tamil.  *Journal of the International Neuropsychological Society*. 2023;29(10):964-971.DOI:10.1017/S135561772300067X

[Access](https://psyarxiv.com/agb3j/) **Webb, S. S.**, & Demeyere, N. (2023). Predictive validity of the Oxford Digital Multiple Errands Test (OxMET) for functional outcomes after stroke. *Neuropsychological Rehabilitation*, [DOI:10.1080/09602011.2023.2247152](https://doi.org/10.1080/09602011.2023.2247152)  

[Access](https://healthopenresearch.org/articles/5-8/v1) **Webb, S. S**, Carrick, C, Kusec, A, &  Demeyere, N. (2023). Introducing the Tele-OCS: A validated remotely administered version of The Oxford Cognitive Screen  [version 1; peer review: 2 approved with reservations]. *Health Open Res 2023*, 5:8, [DOI: 10.12688/healthopenres.13291.1](https://doi.org/10.12688/healthopenres.13291.1)  

# **2022**
[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/MultiverseExecFunctPaper.pdf) **Webb, S. S.**, & Demeyere, N. (2023). Using multiverse analysis to highlight differences in convergent correlation outcomes due to data analytical and study design choices. *Assessment*,Assessment, 30(6), 1825-1835. [DOI:10.1177/10731911221127904](https://doi.org/10.1177/10731911221127904)

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/FinalOCS-AUPaper.pdf) $*$Sanctuary, C., $*$Hewitt, L., Demeyere, N., Kankkunen, K., Oxenham, V. D., Simpson, D. B., Stolwyk, R. J., Synn, A., **Webb, S.S.**, Marsden, D. L. (2022). The Oxford Cognitive Screen for use with Australian people after stroke (OCS-AU): The adaptation process, and determining cut scores for cognitive impairment using a cross-sectional normative study. *Australian Occupational Therapy Journal*. [DOI:10.1177/10731911221127904](https://doi.org/10.1111/1440-1630.12838).

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/OCSPlusstroke.pdf) **Webb S. S**, Hobden G, Roberts R, Chiu EG, King S, Demeyere N. (2022) Validation of the UK English Oxford cognitive screen-plus in sub-acute and chronic stroke survivors. *European Stroke Journal*. [DOI:  10.1177/23969873221119940](https://doi.org/10.1177/23969873221119940)

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/OxMET-USA_culturaladaption.pdf) **Webb, S.S**., Burns, S.P., Jespersen, A., & Demeyere, N. (2022). Cultural Adaptation Of The Oxford Digital Multiple Errands Test (OxMET) For An English Speaking North American Population. *2022 RESNA Virtual Conference: Driving the Future of Assistive Technology*, USA, [URL: https://www.resna.org/sites/default/files/conference/2022/AgingCognitiveSensory/77_Webb.html](https://www.resna.org/sites/default/files/conference/2022/AgingCognitiveSensory/77_Webb.html)

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/Final%20paper_position.pdf) Burns, S. P., Fleming, T. K., **Webb, S.S.**, Kam, A. S. H., Fielder, J. D., Kim, G. J., ... & Kringle, E. A. (2022). Stroke Recovery During the COVID-19 Pandemic: A Position Paper on Recommendations for Rehabilitation. *Archives of physical medicine and rehabilitation*, [DOI: 10.1016/j.apmr.2022.04.004](https://doi.org/10.1016/j.apmr.2022.04.004) 

# **2021**
[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/AutoFig_manuscript.pdf) **Webb, S.S.**, Moore, M., Yamshchikova, A., Kozik, V., Duta, M., Voiculescu, I., & Demeyere, N (2021) Validation of an Automated Scoring Program for a digital Complex Figure Copy Task within healthy ageing and stroke, *Neuropsychology*, [DOI: 10.1037/neu0000748](https://doi.apa.org/doiLanding?doi=10.1037%2Fneu0000748) 

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/CovidSurvey.pdf) **Webb, S.S.**., Kontou, E.,  & Demeyere, N. (2021) The COVID-19 pandemic altered the modality, but not the frequency, of formal cognitive assessment, *Disability and Rehabilitation*, [DOI: 10.1080/09638288.2021.1963855](https://www.tandfonline.com/doi/full/10.1080/09638288.2021.1963855) 

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/OxMETPsychometrics.pdf) **Webb, S.S.**, Jespersen, A.,Chiu, E. G., Payne, F., Basting, R.,  Duta, M. D., & Demeyere, N. (2021) The Oxford digital multiple errands test (OxMET): Validation of a simplified computer tablet based multiple errands test, *Neuropsychological Rehabilitation*, 
[DOI: 10.1080/09602011.2020.1862679](https://www.tandfonline.com/doi/full/10.1080/09602011.2020.1862679) 

[PDF](https://github.com/SamSWebb/SamSWebb.github.io/blob/master/pdfs/IntroOCS-Plus.pdf) Demeyere, N., Haupt, M., **Webb, S.S**. et al. Introducing the tablet-based Oxford Cognitive Screen-Plus (OCS-Plus) as an assessment tool for subtle cognitive impairments. *Scientific Reports*, 11, 8000 (2021). [DOI: 10.1038/s41598-021-87287-8](https://www.nature.com/articles/s41598-021-87287-8) 



